ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1

    odom0: /odom
    odom0_config: [true, true, false,
                   false, false, true,
                   true, true, false,
                   false, false, true,
                   false, false, false]

    imu0: /imu/data
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]

    imu0_differential: true
    imu0_relative: true

    base_link_frame: base_footprint
    odom_frame: odom
    world_frame: map

    publish_tf: false
    map_frame: map
